#
# Name: pikachu
# Date: 14 feb 2016
# 
# Note: Makefiles begin with a captal M
#   Indentation MUST be with a tab
#
# tagets build, test, clean and submit are required.
# 

COPTS= 
#COPTS= -Wall

PASSFILE= mypasswords.txt
SERVER= localhost

build:
	make mradius

mradius: mradius.c mradius.h utils.o mradius-client.o mradius-server.o
	cc ${COPTS} -o $@ -lcrypto $< utils.o mradius-client.o mradius-server.o

mradius-client.o: mradius-client.c mradius.h
	cc ${COPTS} -c -o $@ $< 
	
mradius-server.o: mradius-server.c mradius.h
	cc ${COPTS} -c -o $@ $< 

utils.o: utils.c mradius.h
	cc ${COPTS} -c -o $@ $< 

run-server-nr:
	./mradius -vLR ${PASSFILE}
	./mradius -vLR ${PASSFILE}
	
run-server:
	./mradius -v ${PASSFILE}
	
run-client-nr:
	./mradius -vR -h ${SERVER} pikachu LaaOVTXLgtk0
	sleep 1
	./mradius -vR -h ${SERVER} pikachu wrong
	sleep 1
	./mradius -vR -h ${SERVER} nonexistant none

run-client-v:
	./mradius -v -h ${SERVER} pikachu LaaOVTXLgtk0
	sleep 1
	./mradius -v -h ${SERVER} pikachu wrong
	sleep 1
	./mradius -v -h ${SERVER} nonexistant none

run-client-x:
	./mradius -h ${SERVER} pikachu LaaOVTXLgtk0
	sleep 1
	./mradius -h ${SERVER} pikachu wrong
	sleep 1
	./mradius -h ${SERVER} wonderwoman refs385tike
	sleep 1
	./mradius -h ${SERVER} wonderwoman wrong
	sleep 1
	./mradius -h ${SERVER} nonexistant none
	sleep 1
	./mradius -h ${SERVER} nameonly

run-client:
	( make run-client-x ) &> basic-test.out
	diff basic-test.ref basic-test.out

making-basic-ref:
	@echo make run-server 
	make run-client &> basic-test.ref
	
clean:
	-rm mradius utils.o mradius-client.o mradius-server.o

submit:
	@echo svn add your work
	svn commit -m "submitted for grading"


